### ISSUE TITLE
NPE when opening a file or changing theme

### ISSUE THREAD

**Issue by joffrey-bion** [joffrey-bion/fx-log#57]
This occurred when opening a new file or when changing the theme:

```
java.lang.NullPointerException: Cannot bind to null
at javafx.beans.property.ObjectPropertyBase.bind(Unknown Source)
at javafx.css.StyleableObjectProperty.bind(Unknown Source)
at org.hildan.fxlog.coloring.StyleRule.bindNodeForeground(StyleRule.java:114)
at org.hildan.fxlog.coloring.StyleRule.bindStyleIfMatches(StyleRule.java:99)
at org.hildan.fxlog.coloring.Colorizer.bindStyle(Colorizer.java:70)
at org.hildan.fxlog.view.StyledTableCell.updateItem(StyledTableCell.java:47)
at org.hildan.fxlog.view.StyledTableCell.updateItem(StyledTableCell.java:17)
at javafx.scene.control.TableCell.updateItem(Unknown Source)
at javafx.scene.control.TableCell.indexChanged(Unknown Source)
at javafx.scene.control.IndexedCell.updateIndex(Unknown Source)
at com.sun.javafx.scene.control.skin.TableRowSkinBase.updateCells(Unknown Source)
at com.sun.javafx.scene.control.skin.TableRowSkinBase.init(Unknown Source)
at com.sun.javafx.scene.control.skin.TableRowSkin.<init>(Unknown Source)
at javafx.scene.control.TableRow.createDefaultSkin(Unknown Source)
at javafx.scene.control.Control.impl_processCSS(Unknown Source)
at javafx.scene.Parent.impl_processCSS(Unknown Source)
at javafx.scene.Parent.impl_processCSS(Unknown Source)
at javafx.scene.Parent.impl_processCSS(Unknown Source)
at javafx.scene.control.Control.impl_processCSS(Unknown Source)
at javafx.scene.Parent.impl_processCSS(Unknown Source)
at javafx.scene.Node.processCSS(Unknown Source)
at javafx.scene.Scene.doCSSPass(Unknown Source)
at javafx.scene.Scene.access$3600(Unknown Source)
at javafx.scene.Scene$ScenePulseListener.pulse(Unknown Source)
at com.sun.javafx.tk.Toolkit.lambda$runPulse$30(Unknown Source)
at java.security.AccessController.doPrivileged(Native Method)
at com.sun.javafx.tk.Toolkit.runPulse(Unknown Source)
at com.sun.javafx.tk.Toolkit.firePulse(Unknown Source)
at com.sun.javafx.tk.quantum.QuantumToolkit.pulse(Unknown Source)
at com.sun.javafx.tk.quantum.QuantumToolkit.pulse(Unknown Source)
at com.sun.javafx.tk.quantum.QuantumToolkit.lambda$runToolkit$404(Unknown Source)
at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(Unknown Source)
at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
at com.sun.glass.ui.win.WinApplication.lambda$null$148(Unknown Source)
at java.lang.Thread.run(Unknown Source)
```

**Comment by joffrey-bion** [comment]
Probably because of a config version issue. This should be solved by https://github.com/joffrey-bion/fx-log/issues/56.
